#####################
####### Micronaut
#####################
micronaut.application.name=reddit-trends-analyzer
micronaut.server.port=8082
micronaut.serde.deserialization.ignore-unknown=true
#####################
####### DynamoDB
#####################
aws.dynamodb.endpoint-override=http://localhost:8000
aws.region=eu-west-3
aws.credentials.static.access-key-id=DUMMYKEY
aws.credentials.static.secret-access-key=DUMMYSECRET
#####################
####### Custom
#####################
default-subreddit=socialmedia
posts-scheduling.enabled=false
#####################
####### Ollama
#####################
ollama.host=http://localhost:11434
ollama.model=gemma3:1b