micronaut.application.name=reddit-trends-analyzer
micronaut.server.port=8081
aws.dynamodb.endpoint-override=http://localhost:8000
aws.region=eu-west-3
aws.credentials.static.access-key-id=DUMMYKEY
aws.credentials.static.secret-access-key=DUMMYSECRET
micronaut.serde.deserialization.ignore-unknown=true
default-subreddit=socialmedia